version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: northwind_db
    environment:
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: playground
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    volumes:
      - ./datasets/northwind_setup.sql:/docker-entrypoint-initdb.d/northwind.sql
